name: py36pt110
channels:
  - sahni
  - pytorch
  - menpo
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - brotlipy=0.7.0=py36h7b6447c_1000
  - ca-certificates=2020.6.24=0
  - certifi=2020.6.20=py36_0
  - cffi=1.13.2=py36h2e261b9_0
  - chardet=3.0.4=py36_1003
  - cloudpickle=1.2.2=py_0
  - colorama=0.4.1=py36_0
  - cryptography=2.9.2=py36h1ba5d50_0
  - cudatoolkit=10.0.130=0
  - cycler=0.10.0=py36_0
  - cython=0.29.20=py36he6710b0_0
  - cytoolz=0.10.1=py36h7b6447c_0
  - dask-core=2.8.0=py_0
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.1=py_0
  - easydict=1.9=py_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.63.1=h5a9c865_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.10.0=py36hd6299e0_1
  - hdf5=1.10.6=hb1b8bf9_0
  - icu=58.2=h9c2bf20_1
  - idna=2.10=py_0
  - imageio=2.6.1=py36_0
  - intel-openmp=2019.4=243
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.1.0=py36he6710b0_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - matplotlib=3.1.1=py36h5429711_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.0.15=py36ha843d7b_0
  - mkl_random=1.1.0=py36hd6b4f25_0
  - mpmath=1.1.0=py36_0
  - ncurses=6.1=he6710b0_1
  - networkx=2.4=py_0
  - ninja=1.9.0=py36hfd86e86_0
  - nltk=3.4.5=py36_0
  - numpy=1.17.3=py36hd14ec0e_0
  - numpy-base=1.17.3=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - opencv3=3.1.0=py36_0
  - openssl=1.1.1g=h7b6447c_0
  - pcre=8.43=he6710b0_0
  - pillow=6.2.1=py36h34e0f95_0
  - pip=20.1.1=py36_1
  - progress=1.5=py36_0
  - pycparser=2.19=py36_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.5=py_0
  - pyqt=5.9.2=py36h05f1152_2
  - pysocks=1.7.1=py36_0
  - python=3.6.9=h265db76_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytorch=1.1.0=py3.6_cuda10.0.130_cudnn7.5.1_0
  - pytz=2019.3=py_0
  - pywavelets=1.1.1=py36h7b6447c_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - requests=2.24.0=py_0
  - scikit-image=0.15.0=py36he6710b0_0
  - setuptools=41.6.0=py36_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.13.0=py36_0
  - sqlite=3.30.1=h7b6447c_0
  - sympy=1.6.1=py36_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - torchutils=0.0.4=py36_0
  - torchvision=0.3.0=py36_cu10.0.130_1
  - tornado=6.0.3=py36h7b6447c_0
  - tqdm=4.38.0=py_0
  - urllib3=1.25.9=py_0
  - wheel=0.33.6=py36_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - msgpack==1.0.0
    - opencv-python==4.1.2.30
    - protobuf==3.10.0
    - pycocotools==2.0
    - pyyaml==5.3.1
    - scipy==1.1.0
    - setproctitle==1.1.10
    - tensorboardx==1.9
prefix: /home/truppr/anaconda3/envs/py36pt110

